version: '3'
services:
  mysql:
    container_name: prestashop_db
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: prestashop_db
      DB_NAME: $MYSQL_DATABASE
      DB_USER: $MYSQL_USER
      DB_PASSWD: $MYSQL_PASSWORD
      PS_FOLDER_ADMIN: $PS_FOLDER_ADMIN
      PS_FOLDER_INSTALL: $PS_FOLDER_INSTALL
      ADMIN_MAIL : $ADMIN_MAIL
      ADMIN_PASSWD : $ADMIN_PASSWD
    networks:
      - prestashop_network
    volumes:
      - type: bind
        source: ./src/modules/strawberry-module # local path to the module
        target: /var/www/html/modules/strawberry-module # path to be mounted in the container
      - type: bind
        source: ./src/themes/strawberry-theme # local path to the theme
        target:  /var/www/html/themes/strawberry-theme # path to be mounted in the container
      - psdata:/var/www/html
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: prestashop_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: prestashop_db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - 8081:80
networks:
  prestashop_network:
volumes:
  psdata:
  dbdata: